package GUI;

import java.awt.Color;
import javax.swing.JOptionPane;
import manejodearchivos.Abrir;
import manejodearchivos.Guardar;

public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        this.setSize(800, 600);
        //Instanciar el lienzo y agregarlo a la ventana principal
        lienzo = new Lienzo();
        lienzo.setSize(this.getSize());
        lienzo.setLocation(0, 40);
        lienzo.setBackground(Color.WHITE);
        this.add(lienzo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraHerramientas = new javax.swing.JToolBar();
        botonSeleccionar = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();
        separador1 = new javax.swing.JToolBar.Separator();
        agregarAgent = new javax.swing.JButton();
        agregarCapabilitie = new javax.swing.JButton();
        agregarRole = new javax.swing.JButton();
        agregarGoal = new javax.swing.JButton();
        separador2 = new javax.swing.JToolBar.Separator();
        agregarPossesses = new javax.swing.JButton();
        agregarRequires = new javax.swing.JButton();
        agregarAchieves = new javax.swing.JButton();
        menu = new javax.swing.JMenuBar();
        nuevoArchivo = new javax.swing.JMenu();
        menuNuevo = new javax.swing.JMenuItem();
        menuAbrir = new javax.swing.JMenuItem();
        menuGuardar = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Meta-modelo OMACS");
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        barraHerramientas.setRollover(true);
        barraHerramientas.setMinimumSize(new java.awt.Dimension(400, 40));
        barraHerramientas.setPreferredSize(new java.awt.Dimension(400, 40));

        botonSeleccionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons/SelectElement.png"))); // NOI18N
        botonSeleccionar.setToolTipText("Seleccionar objeto");
        botonSeleccionar.setFocusable(false);
        botonSeleccionar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonSeleccionar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSeleccionarActionPerformed(evt);
            }
        });
        barraHerramientas.add(botonSeleccionar);

        botonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons/DeleteElement.png"))); // NOI18N
        botonEliminar.setToolTipText("Eliminar objeto");
        botonEliminar.setFocusable(false);
        botonEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });
        barraHerramientas.add(botonEliminar);
        barraHerramientas.add(separador1);

        agregarAgent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons/Agent.png"))); // NOI18N
        agregarAgent.setToolTipText("Agregar Agent");
        agregarAgent.setFocusable(false);
        agregarAgent.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        agregarAgent.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        agregarAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarAgentActionPerformed(evt);
            }
        });
        barraHerramientas.add(agregarAgent);

        agregarCapabilitie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons/Capabilitie.png"))); // NOI18N
        agregarCapabilitie.setToolTipText("Agregar Capabilitie");
        agregarCapabilitie.setFocusable(false);
        agregarCapabilitie.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        agregarCapabilitie.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        agregarCapabilitie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarCapabilitieActionPerformed(evt);
            }
        });
        barraHerramientas.add(agregarCapabilitie);

        agregarRole.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons/Role.png"))); // NOI18N
        agregarRole.setToolTipText("Agregar Role");
        agregarRole.setFocusable(false);
        agregarRole.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        agregarRole.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        agregarRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarRoleActionPerformed(evt);
            }
        });
        barraHerramientas.add(agregarRole);

        agregarGoal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons/Goal.png"))); // NOI18N
        agregarGoal.setToolTipText("Agregar Goal");
        agregarGoal.setFocusable(false);
        agregarGoal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        agregarGoal.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        agregarGoal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarGoalActionPerformed(evt);
            }
        });
        barraHerramientas.add(agregarGoal);
        barraHerramientas.add(separador2);

        agregarPossesses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons/possesses.png"))); // NOI18N
        agregarPossesses.setToolTipText("Agregar Possesses");
        agregarPossesses.setFocusable(false);
        agregarPossesses.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        agregarPossesses.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        agregarPossesses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarPossessesActionPerformed(evt);
            }
        });
        barraHerramientas.add(agregarPossesses);

        agregarRequires.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons/requires.png"))); // NOI18N
        agregarRequires.setToolTipText("Agregar Requires");
        agregarRequires.setFocusable(false);
        agregarRequires.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        agregarRequires.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        agregarRequires.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarRequiresActionPerformed(evt);
            }
        });
        barraHerramientas.add(agregarRequires);

        agregarAchieves.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons/achieves.png"))); // NOI18N
        agregarAchieves.setToolTipText("Agregar Achieves");
        agregarAchieves.setFocusable(false);
        agregarAchieves.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        agregarAchieves.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        agregarAchieves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarAchievesActionPerformed(evt);
            }
        });
        barraHerramientas.add(agregarAchieves);

        menu.setBackground(new java.awt.Color(255, 255, 255));

        nuevoArchivo.setText("Archivo");

        menuNuevo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuNuevo.setText("Nuevo modelo");
        menuNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNuevoActionPerformed(evt);
            }
        });
        nuevoArchivo.add(menuNuevo);

        menuAbrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuAbrir.setText("Abrir modelo");
        menuAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAbrirActionPerformed(evt);
            }
        });
        nuevoArchivo.add(menuAbrir);

        menuGuardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuGuardar.setText("Guardar modelo");
        menuGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGuardarActionPerformed(evt);
            }
        });
        nuevoArchivo.add(menuGuardar);

        menuSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menuSalir.setText("Cerrar aplicaión");
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });
        nuevoArchivo.add(menuSalir);

        menu.add(nuevoArchivo);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(barraHerramientas, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(barraHerramientas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(339, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNuevoActionPerformed
        lienzo.limpiarLienzo();
    }//GEN-LAST:event_menuNuevoActionPerformed

    private void menuAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAbrirActionPerformed
        Abrir abrir = new Abrir();
        lienzo.setListaNodos(abrir.getListaNodos());
        lienzo.setListaArcos(abrir.getListaArcos());
        lienzo.repaint();
    }//GEN-LAST:event_menuAbrirActionPerformed

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuSalirActionPerformed

    private void botonSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSeleccionarActionPerformed
        botonSeleccionado = "Seleccionar";
    }//GEN-LAST:event_botonSeleccionarActionPerformed

    private void agregarGoalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarGoalActionPerformed
        botonSeleccionado = "Goal";
    }//GEN-LAST:event_agregarGoalActionPerformed

    private void agregarRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarRoleActionPerformed
        botonSeleccionado = "Role";
    }//GEN-LAST:event_agregarRoleActionPerformed

    private void agregarCapabilitieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarCapabilitieActionPerformed
        botonSeleccionado = "Capabilitie";
    }//GEN-LAST:event_agregarCapabilitieActionPerformed

    private void agregarAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarAgentActionPerformed
        botonSeleccionado = "Agent";
    }//GEN-LAST:event_agregarAgentActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        lienzo.setSize(this.getSize());
    }//GEN-LAST:event_formComponentResized

    private void agregarPossessesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarPossessesActionPerformed
        botonSeleccionado = "Possesses";
    }//GEN-LAST:event_agregarPossessesActionPerformed

    private void agregarRequiresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarRequiresActionPerformed
        botonSeleccionado = "Requires";
    }//GEN-LAST:event_agregarRequiresActionPerformed

    private void agregarAchievesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarAchievesActionPerformed
        botonSeleccionado = "Achieves";
    }//GEN-LAST:event_agregarAchievesActionPerformed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        botonSeleccionado = "Eliminar";
    }//GEN-LAST:event_botonEliminarActionPerformed

    private void menuGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGuardarActionPerformed
        Guardar guardar = new Guardar();
        guardar.GuardarArchivo(lienzo.getListaNodos(), lienzo.getListaArcos());
        JOptionPane.showMessageDialog(null, "Archivo guardado");
    }//GEN-LAST:event_menuGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });  
    }
    
    //String para identificar el botón seleccionado de la barra de herramientas
    protected static String botonSeleccionado = null;
    //Lienzo para hacer el gráfico
    private Lienzo lienzo;
    
    // COMPONENTES DEL FRAME
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarAchieves;
    private javax.swing.JButton agregarAgent;
    private javax.swing.JButton agregarCapabilitie;
    private javax.swing.JButton agregarGoal;
    private javax.swing.JButton agregarPossesses;
    private javax.swing.JButton agregarRequires;
    private javax.swing.JButton agregarRole;
    private javax.swing.JToolBar barraHerramientas;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonSeleccionar;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenuItem menuAbrir;
    private javax.swing.JMenuItem menuGuardar;
    private javax.swing.JMenuItem menuNuevo;
    private javax.swing.JMenuItem menuSalir;
    private javax.swing.JMenu nuevoArchivo;
    private javax.swing.JToolBar.Separator separador1;
    private javax.swing.JToolBar.Separator separador2;
    // End of variables declaration//GEN-END:variables
}

